[metadata]
name = "know-github-view"
description = "Browse GitHub repos you have interacted with"

[source]
command = "know browse github --format television"
ansi = true

[preview]
command = "know browse github --format television-preview --entry '{}'"

[keybindings]
enter = "actions:open-repo"

[actions.open-repo]
description = "Browse issues, PRs and discussions for this repo"
command = "tv --ansi --source-command=\"know browse github-activity --selected-row '{}' --format television\" --preview-command=\"know browse github-activity --selected-row '{}' --format television-preview --entry '{}'\""
mode = "execute"
